-- weddings Table
CREATE TABLE weddings (
    weddingID VARCHAR(255),
    lang ENUM('as', 'bn', 'gu', 'hi', 'kn', 'ml', 'mr', 'ne', 'or', 'pa', 'ta', 'te', 'ur', 'en'),
    domain VARCHAR(255),
    weddingName VARCHAR(255),
    from_role ENUM('bride', 'groom'),
    brideName VARCHAR(255),
    groomName VARCHAR(255),
    brideQualifications VARCHAR(255),
    groomQualifications VARCHAR(255),
    brideBio VARCHAR(255),
    groomBio VARCHAR(255),
    timeline JSON,
    hosts JSON,
    textMessage TEXT,
    template VARCHAR(255),
    tier ENUM('free', 'basic', 'premium', 'custom'),
    videoMessage VARCHAR(255),
    music VARCHAR(255),
    youtube VARCHAR(255),
    accommodation TEXT,
    travel TEXT,
    phone VARCHAR(15),
    host VARCHAR(255) NOT NULL,
    partner VARCHAR(255) NOT NULL,
    manager VARCHAR(255) NOT NULL,
    createdAt DATETIME,
    status ENUM('pending', 'accepted', 'completed'),
    PRIMARY KEY (weddingID, lang),
    FOREIGN KEY (host) REFERENCES users(email),
    FOREIGN KEY (partner) REFERENCES users(email),
    FOREIGN KEY (manager) REFERENCES users(email)
);
